In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'pandas'

In [27]:
#import all datasets in Data folder
exec_data = pd.read_csv('Data/1. exec_data_01-01-2024.csv')
trades_data = pd.read_csv('Data/2. trades_data_01-01-2024.csv')
spreads_data = pd.read_csv('Data/3. spreads_data_01-01-2024.csv')
listingId_data = pd.read_csv('Data/listingId_ref_data_01-01-2024.csv')
market_data = pd.read_csv('Data/markets_ref_data_01-01-2024.csv')
metrics_data = pd.read_csv('Data/metrics_ref_data_01-01-2024.csv')

In [20]:
exec_data

,Unnamed: 0,ObjectId,Date,ExecutedCount|Ask,ExecutedVolume|Ask,ExecutedCount|Bid,ExecutedVolume|Bid,QuoteToTrade
0,0,378320396,2022-04-21,171.0,18160.0,206.0,15116.0,37.123675
1,1,378320397,2022-04-21,114.0,2179.0,145.0,3475.0,57.069767
2,2,378320398,2022-04-21,594.0,214531.0,515.0,197181.0,38.236633
3,3,378320399,2022-04-21,23.0,434.0,9.0,446.0,26.148148
4,4,378320400,2022-04-21,112.0,25931.0,106.0,24475.0,46.186567
...,...,...,...,...,...,...,...,...
2322622,2322622,293980477,2023-06-19,0.0,0.0,2.0,100000.0,24.000000
2322623,2322623,294005779,2023-06-19,483.0,254540.0,546.0,89662.0,41.411079
2322624,2322624,294019025,2023-06-19,16.0,2045.0,110.0,91133.0,32.833333
2322625,2322625,294025227,2023-06-19,0.0,0.0,6.0,1112.0,19.500000
2322626,2322626,294025249,2023-06-19,323.0,154669.0,447.0,140703.0,14.432468

In [21]:
trades_data

,ObjectId,Date,TradeCount|Dark,TradeNotional|Dark,TradeVolume|Dark,TradeCount|Lit,TradeNotional|Lit,TradeVolume|Lit,TradeCount|Bi,TradeNotional|Bi,TradeVolume|Bi,TradeCount|Non,TradeNotional|Non,TradeVolume|Non
0,121210,2022-01-04,13,2.148310e+05,5820,10247,8.737934e+07,2369622,1108,7.185000e+06,195323,40,1.323060e+07,361640
1,121211,2022-01-04,720,8.310871e+06,340903,4427,2.560519e+07,1049169,381,2.955314e+06,120972,17,2.705625e+06,110945
2,121212,2022-01-04,0,0.000000e+00,0,2841,1.569295e+07,423516,292,1.648966e+06,44400,18,2.050769e+06,55546
3,121213,2022-01-04,2,1.191131e+04,166,4923,3.480470e+07,478605,573,3.174120e+07,435326,46,6.324727e+07,867152
4,121214,2022-01-04,17,1.187877e+05,7356,2570,1.137731e+07,698645,297,5.955045e+06,367167,43,3.689857e+06,226754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6125717,294906403,2022-05-24,0,0.000000e+00,0,0,0.000000e+00,0,0,0.000000e+00,0,0,0.000000e+00,0
6125718,294906404,2022-05-24,0,0.000000e+00,0,0,0.000000e+00,0,0,0.000000e+00,0,0,0.000000e+00,0
6125719,294906406,2022-05-24,0,0.000000e+00,0,0,0.000000e+00,0,0,0.000000e+00,0,0,0.000000e+00,0
6125720,294906408,2022-05-24,0,0.000000e+00,0,0,0.000000e+00,0,0,0.000000e+00,0,0,0.000000e+00,0
6125721,294906409,2022-05-24,0,0.000000e+00,0,0,0.000000e+00,0,0,0.000000e+00,0,0,0.000000e+00,0

In [22]:
spreads_data

,ObjectId,Date,Spread|AbsLastTicks,Spread|AbsMeanTicks,Spread|AbsTWATicks,Spread|AbsVWATicks,Spread|AbsLast,Spread|AbsMean,Spread|RelLast,Spread|RelMean,Spread|RelTWA,Spread|RelVWA,Spread|AbsTWA,Spread|AbsVWA
0,332696,2023-12-12,8.0,6.649068,6.385427,6.643901,0.0800,0.074130,80.726539,74.405527,74.397975,76.188965,0.074181,0.076031
1,332702,2023-12-12,1.0,2.065306,1.828158,2.124962,0.0050,0.010327,20.682523,42.578794,37.688848,43.788265,0.009141,0.010625
2,332721,2023-12-12,2.0,1.746056,1.588260,1.864572,0.0100,0.008730,3.333333,2.904776,2.641651,3.103410,0.007941,0.009323
3,342472,2023-12-12,1.0,2.594835,2.324135,2.579745,0.0050,0.012974,11.897680,30.602508,27.366729,30.436672,0.011621,0.012899
4,342476,2023-12-12,9.0,9.639475,7.220978,10.147722,0.0900,0.096395,18.350494,19.636165,14.682784,20.679485,0.072210,0.101477
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3028064,408359765,2023-01-11,29.0,41.489614,30.493034,139.526752,0.0145,0.020844,29.672072,42.538445,31.159391,144.216801,0.015301,0.070685
3028065,411165002,2023-01-11,7.0,8.304102,7.847684,8.171270,0.0700,0.083041,32.964445,39.274450,37.147155,38.525137,0.078477,0.081713
3028066,412582410,2023-01-11,50.0,49.649194,49.880816,53.276869,0.2500,0.248246,93.005952,91.996636,92.259297,98.687161,0.249404,0.266384
3028067,412582411,2023-01-11,56.0,56.076583,55.786047,60.402023,0.2800,0.280383,92.378753,92.093027,91.413363,99.147149,0.278930,0.302010
3028068,412582412,2023-01-11,55.0,56.206231,55.992266,60.611959,0.2750,0.281031,90.781547,92.596678,92.202348,99.841554,0.279961,0.303060

In [15]:
print(len(exec_data), len(trades_data), len(spreads_data))

2322627 6125722 3028069

In [17]:
#see how many unique objects are in the objectId column in  exec_data 
exec_data['ObjectId'].nunique()

6691

In [18]:
#see how many unique objects are in the objectId column in  trades_data
trades_data['ObjectId'].nunique()

13071

In [19]:
#see how many unique objects are in the objectId column in  spreads_data
spreads_data['ObjectId'].nunique()

7407

In [21]:
#see how many numbers in ObjectId column in exec_data matches with ObjectId column in trades_data and match with ObjectId in spreads_data
len(set(exec_data['ObjectId']).intersection(set(trades_data['ObjectId'])).intersection(set(spreads_data['ObjectId'])))

6442

In [22]:
#concatenate exec_data, trades_data and spreads_data 
data_concatenated = pd.concat([exec_data, trades_data, spreads_data])

In [26]:
# make the setting so all columns are displayed
pd.set_option('display.max_columns', None)

In [35]:
#remove unnamed:0 column
data_concatenated = data_concatenated.loc[:, ~data_concatenated.columns.str.contains('^Unnamed')]

In [ ]:
#export the concatenated data to a csv file
data_concatenated.to_csv('Data/concatenated_data.csv', index=False)

In [37]:
data_concatenated

,ObjectId,Date,ExecutedCount|Ask,ExecutedVolume|Ask,ExecutedCount|Bid,ExecutedVolume|Bid,QuoteToTrade,TradeCount|Dark,TradeNotional|Dark,TradeVolume|Dark,TradeCount|Lit,TradeNotional|Lit,TradeVolume|Lit,TradeCount|Bi,TradeNotional|Bi,TradeVolume|Bi,TradeCount|Non,TradeNotional|Non,TradeVolume|Non,Spread|AbsLastTicks,Spread|AbsMeanTicks,Spread|AbsTWATicks,Spread|AbsVWATicks,Spread|AbsLast,Spread|AbsMean,Spread|RelLast,Spread|RelMean,Spread|RelTWA,Spread|RelVWA,Spread|AbsTWA,Spread|AbsVWA
0,378320396,2022-04-21,171.0,18160.0,206.0,15116.0,37.123675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,378320397,2022-04-21,114.0,2179.0,145.0,3475.0,57.069767,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,378320398,2022-04-21,594.0,214531.0,515.0,197181.0,38.236633,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,378320399,2022-04-21,23.0,434.0,9.0,446.0,26.148148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,378320400,2022-04-21,112.0,25931.0,106.0,24475.0,46.186567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3028064,408359765,2023-01-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.0,41.489614,30.493034,139.526752,0.0145,0.020844,29.672072,42.538445,31.159391,144.216801,0.015301,0.070685
3028065,411165002,2023-01-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,8.304102,7.847684,8.171270,0.0700,0.083041,32.964445,39.274450,37.147155,38.525137,0.078477,0.081713
3028066,412582410,2023-01-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,49.649194,49.880816,53.276869,0.2500,0.248246,93.005952,91.996636,92.259297,98.687161,0.249404,0.266384
3028067,412582411,2023-01-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.0,56.076583,55.786047,60.402023,0.2800,0.280383,92.378753,92.093027,91.413363,99.147149,0.278930,0.302010
3028068,412582412,2023-01-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.0,56.206231,55.992266,60.611959,0.2750,0.281031,90.781547,92.596678,92.202348,99.841554,0.279961,0.303060

In [38]:
listingId_data

,Date,ListingId,InstrumentId,BIGI,CurrencyCode,Description,DisplayName,FIGI,FIGIComposite,FIGIShareClass,ISIN,InstrumentType,IsAlive,IsPrimary,MIC,MarketDataLevel,OPOL,OperatingMIC,ReutersInstrumentId,ReutersOrganizationId,ReutersQuoteId,SegmentCode,Ticker
0,2024-08-27,121210,121322,NaN,GBp,ANGLO AMERICAN,ANGLO AMERICAN,BBG000BWF7M0,BBG000BWF7C1,BBG001S5Z1X8,GB00B1XZS820,Equity,True,True,XLON,L3,XLON,NaN,256012.0,35872.0,1049594.0,SET1,AAL
1,2024-08-27,121211,121323,NaN,GBp,A.B.FOOD,A.B.FOOD,BBG000BD3SC0,BBG000BD3RV1,BBG001S60Z87,GB0006731235,Equity,True,True,XLON,L3,XLON,NaN,360516.0,19120.0,1049353.0,SET1,ABF
2,2024-08-27,121212,121324,NaN,GBp,ADMIRAL GRP,ADMIRAL GRP,BBG000PG2GZ0,BBG000PG2G17,BBG001SLBF22,GB00B02J6398,Equity,True,True,XLON,L3,XLON,NaN,18173304.0,3956974.0,18173305.0,SET1,ADM
3,2024-08-27,121213,121325,NaN,GBp,ASHTEAD GRP.,ASHTEAD GRP.,BBG000BD42C6,BBG000BD41Z3,BBG001S610V7,GB0000536739,Equity,True,True,XLON,L3,XLON,NaN,260205.0,19098.0,1081144.0,SET1,AHT
4,2024-08-27,121214,121326,NaN,GBp,ANTOFAGASTA,ANTOFAGASTA,BBG000BD4SC9,BBG000BD4S48,BBG001S612G0,GB0000456144,Equity,True,True,XLON,L3,XLON,NaN,287348.0,24707.0,1079081.0,SET1,ANTO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17396,2024-08-27,689559740,689559743,NaN,EUR,AUDIUS SE NA O.N.,AUDIUS SE NA O.N.,BBG000TWN314,NaN,NaN,DE000A40ET13,Equity,True,True,XETR,L3,XETR,NaN,NaN,NaN,NaN,NaN,3ITN
17397,2024-08-27,690238280,690238281,NaN,INR,SWISS MILITARY CONSUMER GOODS,SWISS MILITARY CONSUMER GOODS,BBG01NZFXZT1,NaN,NaN,INE010C20033,Equity,True,True,XBOM,L2,XBOM,NaN,NaN,NaN,NaN,NaN,E:SWISSM-RE1
17398,2024-08-27,690917603,690917604,NaN,INR,A.F. Enterprises Limited,A.F. Enterprises Limited,BBG01P6VZVM7,NaN,NaN,INE663P20023,Equity,True,True,XBOM,L2,XBOM,NaN,NaN,NaN,NaN,NaN,E:AFEL-RE1
17399,2024-08-27,691024730,691024736,NaN,INR,Aditya Vision Limited,Aditya Vision Limited,BBG00FF8WWZ8,NaN,NaN,INE679V01027,Equity,True,True,XBOM,L2,XBOM,NaN,NaN,NaN,NaN,NaN,E:AVL
17400,2024-08-27,691024733,691024737,NaN,INR,JAYKAY ENTERPRISES LIMITED,JAYKAY ENTERPRISES LIMITED,BBG01NRR2HZ1,NaN,NaN,INE903A20017,Equity,True,True,XBOM,L2,XBOM,NaN,NaN,NaN,NaN,NaN,E:JAYKAY-RE

In [52]:
# concatenate exec_data, trades_data and spreads_data so that the rows are mathed by ObjectId and Date
data_concatenated_grouped = data_concatenated.groupby(['ObjectId', 'Date'])

In [53]:
#display the dataset data_concatenated_grouped
data_concatenated_grouped.first()

                      ExecutedCount|Ask  ExecutedVolume|Ask  \
ObjectId  Date
121210    2022-01-04             5152.0            676249.0
          2022-01-05             4210.0            509652.0
          2022-01-06             5257.0           1185005.0
          2022-01-07             4294.0            557182.0
          2022-01-10             5158.0            581628.0
...                                 ...                 ...
609811092 2023-12-29                NaN                 NaN
609811093 2023-12-28                NaN                 NaN
          2023-12-29               35.0             41000.0
609811094 2023-12-28                NaN                 NaN
          2023-12-29               41.0             72000.0

                      ExecutedCount|Bid  ExecutedVolume|Bid  QuoteToTrade  \
ObjectId  Date
121210    2022-01-04             5095.0           1693373.0     29.555577
          2022-01-05             4740.0           2135540.0     29.859649
          2022-01-06             5051.0            665950.0     34.341679
          2022-01-07             5312.0           1528678.0     33.082744
          2022-01-10             6219.0           1421568.0     30.094162
...                                 ...                 ...           ...
609811092 2023-12-29                NaN                 NaN           NaN
609811093 2023-12-28                NaN                 NaN           NaN
          2023-12-29               19.0             28000.0     29.255814
609811094 2023-12-28                NaN                 NaN           NaN
          2023-12-29               21.0             32000.0     17.830508

                      TradeCount|Dark  TradeNotional|Dark  TradeVolume|Dark  \
ObjectId  Date
121210    2022-01-04             13.0       214831.017245            5820.0
          2022-01-05             23.0       173969.459938            4607.0
          2022-01-06             18.0       213579.324824            5619.0
          2022-01-07             21.0       406039.248472           10482.0
          2022-01-10             15.0       114005.317873            2915.0
...                               ...                 ...               ...
609811092 2023-12-29              0.0            0.000000               0.0
609811093 2023-12-28              0.0            0.000000               0.0
          2023-12-29              0.0            0.000000               0.0
609811094 2023-12-28              0.0            0.000000               0.0
          2023-12-29              0.0            0.000000               0.0

                      TradeCount|Lit  TradeNotional|Lit  TradeVolume|Lit  \
ObjectId  Date
121210    2022-01-04         10247.0       8.737934e+07        2369622.0
          2022-01-05          8951.0       1.002495e+08        2645304.0
          2022-01-06         10308.0       7.021947e+07        1850955.0
          2022-01-07          9608.0       8.107991e+07        2086219.0
          2022-01-10         11377.0       7.800150e+07        2003196.0
...                              ...                ...              ...
609811092 2023-12-29             0.0       0.000000e+00              0.0
609811093 2023-12-28             0.0       0.000000e+00              0.0
          2023-12-29            79.0       2.322715e+05         111000.0
609811094 2023-12-28             0.0       0.000000e+00              0.0
          2023-12-29            77.0       3.068320e+05         143000.0

                      TradeCount|Bi  TradeNotional|Bi  TradeVolume|Bi  \
ObjectId  Date
121210    2022-01-04         1108.0      7.185000e+06        195323.0
          2022-01-05          852.0      5.742003e+06        152968.0
          2022-01-06          988.0      9.248248e+06        243197.0
          2022-01-07          879.0      5.802671e+06        149782.0
          2022-01-10         1224.0      1.318480e+07        337820.0
...                             ...               ...             ...
609811092 2023-12-29            0.0      0.000000e+00             0.0
609811093 2023-12-28            0.0      0.000000e+00             0.0
          2023-12-29            0.0      0.000000e+00             0.0
609811094 2023-12-28            0.0      0.000000e+00             0.0
          2023-12-29            0.0      0.000000e+00             0.0

                      TradeCount|Non  TradeNotional|Non  TradeVolume|Non  \
ObjectId  Date
121210    2022-01-04            40.0       1.323060e+07         361640.0
          2022-01-05            41.0       1.999018e+07         531263.0
          2022-01-06            24.0       5.860724e+06         154509.0
          2022-01-07            28.0       1.773412e+07         457545.0
          2022-01-10            11.0       1.980817e+06          50839.0
...                              ...                ...              ...
609811092 2023-12-29             0.0       0.000000e+00              0.0
609811093 2023-12-28             0.0       0.000000e+00              0.0
          2023-12-29             0.0       0.000000e+00              0.0
609811094 2023-12-28             0.0       0.000000e+00              0.0
          2023-12-29             0.0       0.000000e+00              0.0

                      Spread|AbsLastTicks  Spread|AbsMeanTicks  \
ObjectId  Date
121210    2022-01-04                  3.0             2.318785
          2022-01-05                  3.0             2.441856
          2022-01-06                  3.0             2.373161
          2022-01-07                  3.0             2.877415
          2022-01-10                  2.0             2.481059
...                                   ...                  ...
609811092 2023-12-29                  NaN                  NaN
609811093 2023-12-28                  NaN                  NaN
          2023-12-29                  NaN                  NaN
609811094 2023-12-28                  NaN                  NaN
          2023-12-29                100.0           112.741433

                      Spread|AbsTWATicks  Spread|AbsVWATicks  Spread|AbsLast  \
ObjectId  Date
121210    2022-01-04            2.137613            2.426325            1.50
          2022-01-05            2.283295            2.505062            1.50
          2022-01-06            2.065672            2.526402            1.50
          2022-01-07            2.537810            3.024135            1.50
          2022-01-10            2.239130            2.614339            1.00
...                                  ...                 ...             ...
609811092 2023-12-29                 NaN                 NaN             NaN
609811093 2023-12-28                 NaN                 NaN             NaN
          2023-12-29                 NaN                 NaN             NaN
609811094 2023-12-28                 NaN                 NaN             NaN
          2023-12-29           80.368680          101.631272            0.05

                      Spread|AbsMean  Spread|RelLast  Spread|RelMean  \
ObjectId  Date
121210    2022-01-04        1.159393        4.861055        3.774743
          2022-01-05        1.220928        4.723294        3.897880
          2022-01-06        1.186580        4.741209        3.738283
          2022-01-07        1.438708        4.607233        4.458730
          2022-01-10        1.240530        3.078818        3.818430
...                              ...             ...             ...
609811092 2023-12-29             NaN             NaN             NaN
609811093 2023-12-28             NaN             NaN             NaN
          2023-12-29             NaN             NaN             NaN
609811094 2023-12-28             NaN             NaN             NaN
          2023-12-29        0.056371      232.018561      261.091331

                      Spread|RelTWA  Spread|RelVWA  Spread|AbsTWA  \
ObjectId  Date
121210    2022-01-04       3.485661       3.945419       1.068806
          2022-01-05       3.655581       3.992075       1.141648
          2022-01-06       3.253898       3.980012       1.032836
          2022-01-07       3.931387       4.684262       1.268905
          2022-01-10       3.441379       4.022785       1.119565
...                             ...            ...            ...
609811092 2023-12-29            NaN            NaN            NaN
609811093 2023-12-28            NaN            NaN            NaN
          2023-12-29            NaN            NaN            NaN
609811094 2023-12-28            NaN            NaN            NaN
          2023-12-29     186.144849     235.177260       0.040184

                      Spread|AbsVWA
ObjectId  Date
121210    2022-01-04       1.213163
          2022-01-05       1.252531
          2022-01-06       1.263201
          2022-01-07       1.512068
          2022-01-10       1.307169
...                             ...
609811092 2023-12-29            NaN
609811093 2023-12-28            NaN
          2023-12-29            NaN
609811094 2023-12-28            NaN
          2023-12-29       0.050816

[6125749 rows x 29 columns]

In [ ]:
# make a dataframe from the data_concatenated_grouped
data_concatenated_grouped = pd.DataFrame(data_concatenated_grouped.first())

In [54]:
# Convert grouped object back to a DataFrame
grouped_df = data_concatenated_grouped.apply(lambda x: x)

# Reset index to convert groupby object to a regular DataFrame with multi-level index as columns
grouped_df = grouped_df.reset_index(drop=True)

In [ ]:
grouped_df

In [28]:
# Merging datasets on common columns 'ListingId' and 'Date'
merged_df = exec_data.merge(trades_data, on=['ObjectId', 'Date'], how='outer').merge(spreads_data, on=['ObjectId', 'Date'], how='outer')

In [29]:
merged_df

,Unnamed: 0,ObjectId,Date,ExecutedCount|Ask,ExecutedVolume|Ask,ExecutedCount|Bid,ExecutedVolume|Bid,QuoteToTrade,TradeCount|Dark,TradeNotional|Dark,TradeVolume|Dark,TradeCount|Lit,TradeNotional|Lit,TradeVolume|Lit,TradeCount|Bi,TradeNotional|Bi,TradeVolume|Bi,TradeCount|Non,TradeNotional|Non,TradeVolume|Non,Spread|AbsLastTicks,Spread|AbsMeanTicks,Spread|AbsTWATicks,Spread|AbsVWATicks,Spread|AbsLast,Spread|AbsMean,Spread|RelLast,Spread|RelMean,Spread|RelTWA,Spread|RelVWA,Spread|AbsTWA,Spread|AbsVWA
0,0.0,378320396,2022-04-21,171.0,18160.0,206.0,15116.0,37.123675,0.0,0.0,0.0,324.0,1544302.65,30664.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.322598,2.195458,2.295832,0.10,0.179409,19.900498,35.697271,34.542486,38.416442,0.173571,0.193387
1,1.0,378320397,2022-04-21,114.0,2179.0,145.0,3475.0,57.069767,0.0,0.0,0.0,216.0,808817.20,4664.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.686354,2.285321,3.091760,0.40,0.537271,23.014960,31.009574,26.361832,35.695723,0.457064,0.618352
2,2.0,378320398,2022-04-21,594.0,214531.0,515.0,197181.0,38.236633,0.0,0.0,0.0,954.0,7955666.16,310159.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.311597,2.059402,2.547569,0.02,0.046232,7.766990,18.039498,16.006659,19.843929,0.041188,0.050951
3,3.0,378320399,2022-04-21,23.0,434.0,9.0,446.0,26.148148,0.0,0.0,0.0,28.0,31146.40,776.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,3.890244,3.556415,4.175386,0.60,0.389024,149.625935,97.029793,88.678021,104.176993,0.355641,0.417539
4,4.0,378320400,2022-04-21,112.0,25931.0,106.0,24475.0,46.186567,0.0,0.0,0.0,150.0,872920.20,36742.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.505051,1.428546,1.635950,0.05,0.075253,20.942408,31.661238,30.027170,34.407578,0.071427,0.081798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6125744,NaN,294906406,2022-05-24,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6125745,NaN,294906408,2022-05-24,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6125746,NaN,294906409,2022-05-24,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6125747,NaN,593408857,2023-09-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,19.692308,21.646984,18.579184,0.44,0.393846,1111.111111,1008.668243,1099.248646,955.685915,0.432940,0.371584
6125748,NaN,593409189,2023-09-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.000000,12.000000,12.000000,0.60,0.600000,431.654676,431.654676,431.654676,431.654676,0.600000,0.600000

In [14]:
# show the data for objectId 378320396
merged_df[merged_df['ObjectId'] == 378320396]

,Unnamed: 0,ObjectId,Date,ExecutedCount|Ask,ExecutedVolume|Ask,ExecutedCount|Bid,ExecutedVolume|Bid,QuoteToTrade,TradeCount|Dark,TradeNotional|Dark,...,Spread|AbsTWATicks,Spread|AbsVWATicks,Spread|AbsLast,Spread|AbsMean,Spread|RelLast,Spread|RelMean,Spread|RelTWA,Spread|RelVWA,Spread|AbsTWA,Spread|AbsVWA
0,0.0,378320396,2022-04-21,171.0,18160.0,206.0,15116.0,37.123675,0.0,0.0,...,2.195458,2.295832,0.10,0.179409,19.900498,35.697271,34.542486,38.416442,0.173571,0.193387
74,74.0,378320396,2022-04-22,180.0,14162.0,227.0,19499.0,52.186944,0.0,0.0,...,2.942817,3.708076,0.15,0.166469,30.721966,34.024348,30.103637,37.946641,0.147141,0.185404
143,143.0,378320396,2022-04-25,154.0,14118.0,238.0,27978.0,72.003425,0.0,0.0,...,3.191498,3.558163,0.20,0.179256,42.918455,37.943703,33.792708,37.749201,0.159575,0.177908
212,212.0,378320396,2022-04-26,279.0,25195.0,422.0,28970.0,32.248677,0.0,0.0,...,2.861069,3.574572,0.15,0.160937,30.880082,33.720960,30.032245,37.547176,0.143053,0.178729
278,278.0,378320396,2022-04-27,264.0,19638.0,270.0,22614.0,46.805226,0.0,0.0,...,3.382159,4.095111,0.20,0.226101,39.682540,45.594921,38.993442,47.903906,0.193649,0.238315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2070442,2070442.0,378320396,2023-12-22,80.0,6252.0,130.0,7357.0,36.314961,0.0,0.0,...,2.309522,2.279933,0.10,0.108739,23.364486,25.405726,26.934261,26.644197,0.115476,0.113997
2070519,2070519.0,378320396,2023-12-27,171.0,17263.0,134.0,12049.0,26.797980,0.0,0.0,...,2.458699,2.870284,0.15,0.130900,34.188034,29.891076,28.061562,32.767949,0.122935,0.143514
2070600,2070600.0,378320396,2023-12-28,229.0,27038.0,153.0,11995.0,25.841897,0.0,0.0,...,2.472616,2.684567,0.15,0.132476,34.266134,30.272380,28.239642,30.681849,0.123631,0.134228
2070678,2070678.0,378320396,2023-12-29,135.0,14819.0,71.0,7814.0,23.216783,0.0,0.0,...,2.275316,2.695978,0.25,0.122541,56.401579,27.820650,25.832657,30.600774,0.113766,0.134799
3843738,NaN,378320396,2022-06-06,NaN,NaN,NaN,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
merged_df1 = pd.merge(exec_data, trades_data, on=['ObjectId', 'Date'], how='outer')
merged_df2 = pd.merge(merged_df1, spreads_data, on=['ObjectId', 'Date'], how='outer')

In [24]:
#change settings to display all columns in the dataset
pd.set_option('display.max_columns', None)

In [25]:
merged_df2

,Unnamed: 0,ObjectId,Date,ExecutedCount|Ask,ExecutedVolume|Ask,ExecutedCount|Bid,ExecutedVolume|Bid,QuoteToTrade,TradeCount|Dark,TradeNotional|Dark,TradeVolume|Dark,TradeCount|Lit,TradeNotional|Lit,TradeVolume|Lit,TradeCount|Bi,TradeNotional|Bi,TradeVolume|Bi,TradeCount|Non,TradeNotional|Non,TradeVolume|Non,Spread|AbsLastTicks,Spread|AbsMeanTicks,Spread|AbsTWATicks,Spread|AbsVWATicks,Spread|AbsLast,Spread|AbsMean,Spread|RelLast,Spread|RelMean,Spread|RelTWA,Spread|RelVWA,Spread|AbsTWA,Spread|AbsVWA
0,0.0,378320396,2022-04-21,171.0,18160.0,206.0,15116.0,37.123675,0.0,0.000000,0.0,324.0,1.544303e+06,30664.0,0.0,0.000000,0.0,0.0,0.000000e+00,0.0,1.0,2.322598,2.195458,2.295832,0.10,0.179409,19.900498,35.697271,34.542486,38.416442,0.173571,0.193387
1,1.0,378320397,2022-04-21,114.0,2179.0,145.0,3475.0,57.069767,0.0,0.000000,0.0,216.0,8.088172e+05,4664.0,0.0,0.000000,0.0,0.0,0.000000e+00,0.0,2.0,2.686354,2.285321,3.091760,0.40,0.537271,23.014960,31.009574,26.361832,35.695723,0.457064,0.618352
2,2.0,378320398,2022-04-21,594.0,214531.0,515.0,197181.0,38.236633,0.0,0.000000,0.0,954.0,7.955666e+06,310159.0,0.0,0.000000,0.0,0.0,0.000000e+00,0.0,1.0,2.311597,2.059402,2.547569,0.02,0.046232,7.766990,18.039498,16.006659,19.843929,0.041188,0.050951
3,3.0,378320399,2022-04-21,23.0,434.0,9.0,446.0,26.148148,0.0,0.000000,0.0,28.0,3.114640e+04,776.0,0.0,0.000000,0.0,0.0,0.000000e+00,0.0,6.0,3.890244,3.556415,4.175386,0.60,0.389024,149.625935,97.029793,88.678021,104.176993,0.355641,0.417539
4,4.0,378320400,2022-04-21,112.0,25931.0,106.0,24475.0,46.186567,0.0,0.000000,0.0,150.0,8.729202e+05,36742.0,0.0,0.000000,0.0,0.0,0.000000e+00,0.0,1.0,1.505051,1.428546,1.635950,0.05,0.075253,20.942408,31.661238,30.027170,34.407578,0.071427,0.081798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2322622,2322622.0,293980477,2023-06-19,0.0,0.0,2.0,100000.0,24.000000,0.0,0.000000,0.0,2.0,4.486358e+04,100000.0,7.0,157535.207427,352136.0,0.0,0.000000e+00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2322623,2322623.0,294005779,2023-06-19,483.0,254540.0,546.0,89662.0,41.411079,0.0,0.000000,0.0,1029.0,8.017164e+06,344202.0,42.0,222100.877932,9558.0,44.0,1.945681e+07,829927.0,2.0,2.290870,2.295514,2.365812,2.00,2.585171,10.131712,13.000558,13.915867,13.640969,2.770427,2.711691
2322624,2322624.0,294019025,2023-06-19,16.0,2045.0,110.0,91133.0,32.833333,0.0,0.000000,0.0,126.0,1.822595e+05,93178.0,24.0,38407.067130,19601.0,7.0,6.704948e+04,34277.0,9.0,21.590999,15.580590,16.161322,1.80,4.318200,107.462687,258.015533,186.718872,193.339751,3.116118,3.232264
2322625,2322625.0,294025227,2023-06-19,0.0,0.0,6.0,1112.0,19.500000,1.0,92.907069,233.0,6.0,4.407773e+02,1112.0,31.0,34776.820812,88447.0,0.0,0.000000e+00,0.0,3.0,16.166667,15.315981,13.848783,0.30,1.616667,89.418778,471.369563,448.118354,405.561920,1.531598,1.384878
2322626,2322626.0,294025249,2023-06-19,323.0,154669.0,447.0,140703.0,14.432468,0.0,0.000000,0.0,770.0,7.210252e+05,295372.0,18.0,10283.655458,4283.0,20.0,5.285586e+05,216544.0,2.0,9.731439,3.055818,7.779708,0.40,1.946288,19.102197,93.295788,29.400876,74.663791,0.611164,1.555942

In [30]:
#save the merged data to a csv file
merged_df.to_csv('Data/merged_data1.csv', index=False)

In [18]:
#remove rows where Unamed:0 column is null
merged_df2 = merged_df2.dropna(subset=['Unnamed: 0'])

In [19]:
merged_df2

,Unnamed: 0,ObjectId,Date,ExecutedCount|Ask,ExecutedVolume|Ask,ExecutedCount|Bid,ExecutedVolume|Bid,QuoteToTrade,TradeCount|Dark,TradeNotional|Dark,...,Spread|AbsTWATicks,Spread|AbsVWATicks,Spread|AbsLast,Spread|AbsMean,Spread|RelLast,Spread|RelMean,Spread|RelTWA,Spread|RelVWA,Spread|AbsTWA,Spread|AbsVWA
0,0.0,378320396,2022-04-21,171.0,18160.0,206.0,15116.0,37.123675,0.0,0.000000,...,2.195458,2.295832,0.10,0.179409,19.900498,35.697271,34.542486,38.416442,0.173571,0.193387
1,1.0,378320397,2022-04-21,114.0,2179.0,145.0,3475.0,57.069767,0.0,0.000000,...,2.285321,3.091760,0.40,0.537271,23.014960,31.009574,26.361832,35.695723,0.457064,0.618352
2,2.0,378320398,2022-04-21,594.0,214531.0,515.0,197181.0,38.236633,0.0,0.000000,...,2.059402,2.547569,0.02,0.046232,7.766990,18.039498,16.006659,19.843929,0.041188,0.050951
3,3.0,378320399,2022-04-21,23.0,434.0,9.0,446.0,26.148148,0.0,0.000000,...,3.556415,4.175386,0.60,0.389024,149.625935,97.029793,88.678021,104.176993,0.355641,0.417539
4,4.0,378320400,2022-04-21,112.0,25931.0,106.0,24475.0,46.186567,0.0,0.000000,...,1.428546,1.635950,0.05,0.075253,20.942408,31.661238,30.027170,34.407578,0.071427,0.081798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2322622,2322622.0,293980477,2023-06-19,0.0,0.0,2.0,100000.0,24.000000,0.0,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2322623,2322623.0,294005779,2023-06-19,483.0,254540.0,546.0,89662.0,41.411079,0.0,0.000000,...,2.295514,2.365812,2.00,2.585171,10.131712,13.000558,13.915867,13.640969,2.770427,2.711691
2322624,2322624.0,294019025,2023-06-19,16.0,2045.0,110.0,91133.0,32.833333,0.0,0.000000,...,15.580590,16.161322,1.80,4.318200,107.462687,258.015533,186.718872,193.339751,3.116118,3.232264
2322625,2322625.0,294025227,2023-06-19,0.0,0.0,6.0,1112.0,19.500000,1.0,92.907069,...,15.315981,13.848783,0.30,1.616667,89.418778,471.369563,448.118354,405.561920,1.531598,1.384878
2322626,2322626.0,294025249,2023-06-19,323.0,154669.0,447.0,140703.0,14.432468,0.0,0.000000,...,3.055818,7.779708,0.40,1.946288,19.102197,93.295788,29.400876,74.663791,0.611164,1.555942

In [31]:
#import Data/merged_data1.csv
merged_data = pd.read_csv('Data/merged_data1.csv')

In [ ]:
#delete all rows with 0 and NaN values in all columns except for the Date and ObjectId columns
merged_data = merged_data.dropna(subset=['Unnamed: 0'])