In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#import all datasets in Data folder
exec_data = pd.read_csv('Data/1. exec_data_01-01-2024.csv')
trades_data = pd.read_csv('Data/2. trades_data_01-01-2024.csv')
spreads_data = pd.read_csv('Data/3. spreads_data_01-01-2024.csv')
listingId_data = pd.read_csv('Data/listingId_ref_data_01-01-2024.csv')
market_data = pd.read_csv('Data/markets_ref_data_01-01-2024.csv')
metrics_data = pd.read_csv('Data/metrics_ref_data_01-01-2024.csv')

In [ ]:
# Merging datasets on common columns 'ListingId' and 'Date'
merged_df = exec_data.merge(trades_data, on=['ObjectId', 'Date'], how='outer').merge(spreads_data, on=['ObjectId', 'Date'], how='outer')

In [ ]:
#save the merged data to a csv file
merged_df.to_csv('Data/merged_data1.csv', index=False)

In [3]:
df = pd.read_csv('Data/merged_data1.csv')

In [4]:
# Define columns to check for all 0 or NaN values
columns_to_check = df.columns.difference(['ObjectId', 'Date'])

# Filter out rows where all entries in the columns_to_check are 0 or NaN
df_cleaned = df.loc[~df[columns_to_check].apply(lambda row: (row == 0) | (row.isna())).all(axis=1)]

In [6]:
#change settings so all columns of the dataframe are displayed
pd.set_option('display.max_columns', None)

In [7]:
# Display the resulting DataFrame
df_cleaned

,Unnamed: 0,ObjectId,Date,ExecutedCount|Ask,ExecutedVolume|Ask,ExecutedCount|Bid,ExecutedVolume|Bid,QuoteToTrade,TradeCount|Dark,TradeNotional|Dark,TradeVolume|Dark,TradeCount|Lit,TradeNotional|Lit,TradeVolume|Lit,TradeCount|Bi,TradeNotional|Bi,TradeVolume|Bi,TradeCount|Non,TradeNotional|Non,TradeVolume|Non,Spread|AbsLastTicks,Spread|AbsMeanTicks,Spread|AbsTWATicks,Spread|AbsVWATicks,Spread|AbsLast,Spread|AbsMean,Spread|RelLast,Spread|RelMean,Spread|RelTWA,Spread|RelVWA,Spread|AbsTWA,Spread|AbsVWA
0,0.0,378320396,2022-04-21,171.0,18160.0,206.0,15116.0,37.123675,0.0,0.0,0.0,324.0,1544302.65,30664.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,2.322598,2.195458,2.295832,0.10,0.179409,19.900498,35.697271,34.542486,38.416442,0.173571,0.193387
1,1.0,378320397,2022-04-21,114.0,2179.0,145.0,3475.0,57.069767,0.0,0.0,0.0,216.0,808817.20,4664.0,0.0,0.0,0.0,0.0,0.000000,0.0,2.0,2.686354,2.285321,3.091760,0.40,0.537271,23.014960,31.009574,26.361832,35.695723,0.457064,0.618352
2,2.0,378320398,2022-04-21,594.0,214531.0,515.0,197181.0,38.236633,0.0,0.0,0.0,954.0,7955666.16,310159.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,2.311597,2.059402,2.547569,0.02,0.046232,7.766990,18.039498,16.006659,19.843929,0.041188,0.050951
3,3.0,378320399,2022-04-21,23.0,434.0,9.0,446.0,26.148148,0.0,0.0,0.0,28.0,31146.40,776.0,0.0,0.0,0.0,0.0,0.000000,0.0,6.0,3.890244,3.556415,4.175386,0.60,0.389024,149.625935,97.029793,88.678021,104.176993,0.355641,0.417539
4,4.0,378320400,2022-04-21,112.0,25931.0,106.0,24475.0,46.186567,0.0,0.0,0.0,150.0,872920.20,36742.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.505051,1.428546,1.635950,0.05,0.075253,20.942408,31.661238,30.027170,34.407578,0.071427,0.081798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6122481,NaN,294906436,2022-04-27,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,1.0,7943.000000,4700.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6123422,NaN,294907272,2022-05-05,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,1.0,407578.126509,21500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6124847,NaN,294906436,2022-05-17,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,1.0,5972.400000,3780.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6125747,NaN,593408857,2023-09-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,19.692308,21.646984,18.579184,0.44,0.393846,1111.111111,1008.668243,1099.248646,955.685915,0.432940,0.371584
6125748,NaN,593409189,2023-09-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.000000,12.000000,12.000000,0.60,0.600000,431.654676,431.654676,431.654676,431.654676,0.600000,0.600000

In [8]:
listingId_data

,Date,ListingId,InstrumentId,BIGI,CurrencyCode,Description,DisplayName,FIGI,FIGIComposite,FIGIShareClass,ISIN,InstrumentType,IsAlive,IsPrimary,MIC,MarketDataLevel,OPOL,OperatingMIC,ReutersInstrumentId,ReutersOrganizationId,ReutersQuoteId,SegmentCode,Ticker
0,2024-08-27,121210,121322,NaN,GBp,ANGLO AMERICAN,ANGLO AMERICAN,BBG000BWF7M0,BBG000BWF7C1,BBG001S5Z1X8,GB00B1XZS820,Equity,True,True,XLON,L3,XLON,NaN,256012.0,35872.0,1049594.0,SET1,AAL
1,2024-08-27,121211,121323,NaN,GBp,A.B.FOOD,A.B.FOOD,BBG000BD3SC0,BBG000BD3RV1,BBG001S60Z87,GB0006731235,Equity,True,True,XLON,L3,XLON,NaN,360516.0,19120.0,1049353.0,SET1,ABF
2,2024-08-27,121212,121324,NaN,GBp,ADMIRAL GRP,ADMIRAL GRP,BBG000PG2GZ0,BBG000PG2G17,BBG001SLBF22,GB00B02J6398,Equity,True,True,XLON,L3,XLON,NaN,18173304.0,3956974.0,18173305.0,SET1,ADM
3,2024-08-27,121213,121325,NaN,GBp,ASHTEAD GRP.,ASHTEAD GRP.,BBG000BD42C6,BBG000BD41Z3,BBG001S610V7,GB0000536739,Equity,True,True,XLON,L3,XLON,NaN,260205.0,19098.0,1081144.0,SET1,AHT
4,2024-08-27,121214,121326,NaN,GBp,ANTOFAGASTA,ANTOFAGASTA,BBG000BD4SC9,BBG000BD4S48,BBG001S612G0,GB0000456144,Equity,True,True,XLON,L3,XLON,NaN,287348.0,24707.0,1079081.0,SET1,ANTO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17396,2024-08-27,689559740,689559743,NaN,EUR,AUDIUS SE NA O.N.,AUDIUS SE NA O.N.,BBG000TWN314,NaN,NaN,DE000A40ET13,Equity,True,True,XETR,L3,XETR,NaN,NaN,NaN,NaN,NaN,3ITN
17397,2024-08-27,690238280,690238281,NaN,INR,SWISS MILITARY CONSUMER GOODS,SWISS MILITARY CONSUMER GOODS,BBG01NZFXZT1,NaN,NaN,INE010C20033,Equity,True,True,XBOM,L2,XBOM,NaN,NaN,NaN,NaN,NaN,E:SWISSM-RE1
17398,2024-08-27,690917603,690917604,NaN,INR,A.F. Enterprises Limited,A.F. Enterprises Limited,BBG01P6VZVM7,NaN,NaN,INE663P20023,Equity,True,True,XBOM,L2,XBOM,NaN,NaN,NaN,NaN,NaN,E:AFEL-RE1
17399,2024-08-27,691024730,691024736,NaN,INR,Aditya Vision Limited,Aditya Vision Limited,BBG00FF8WWZ8,NaN,NaN,INE679V01027,Equity,True,True,XBOM,L2,XBOM,NaN,NaN,NaN,NaN,NaN,E:AVL
17400,2024-08-27,691024733,691024737,NaN,INR,JAYKAY ENTERPRISES LIMITED,JAYKAY ENTERPRISES LIMITED,BBG01NRR2HZ1,NaN,NaN,INE903A20017,Equity,True,True,XBOM,L2,XBOM,NaN,NaN,NaN,NaN,NaN,E:JAYKAY-RE

In [10]:
mic_data_subset = listingId_data[['ListingId', 'MIC']]

In [12]:
df_cleaned1 = df_cleaned.merge(mic_data_subset, left_on='ObjectId', right_on='ListingId', how='left')

In [14]:
#drop the ListingId column
df_cleaned1 = df_cleaned1.drop(columns=['ListingId'])

In [15]:
#export the cleaned data to a csv file
df_cleaned1.to_csv('Data/merged_and_cleaned_data.csv', index=False)